### ISSUE TITLE
Missing Alignment to CEDS: Assessment Type (000029)

### ISSUE THREAD

**Issue by johnmannpaul** [Access4LearningNA/specgen_input_na#168] opened 2022-05-19 18:16 UTC
CEDS element 000029 (Assessment Type) as referenced by domain entity Assessments -> Assessment in the Assessment ETL Checklist is missing from Unity-Edfacts Alignment.

**Comment by 4pins** [comment] 2022-05-19 19:43
Map /Assessment​/AssessmentDescriptors​/AssessmentDescriptor should be mapped to CEDS Assessment Type (000029).

**Comment by 4pins** [comment] 2022-07-07 01:38
Duplicate of https://github.com/Access4LearningNA/specgen_input_na/issues/166.

**Comment by tqwhite** [comment] 2022-07-21 19:37
NATB agree it should happen but it has not been done yet.

**Comment by tqwhite** [comment] 2022-07-21 19:37
http://specification.sifassociation.org/Implementation/NA/4.3/AssessmentWorkingGroup.html#obj:Assessment

**Comment by 4pins** [comment] 2022-07-25 22:29
Looks done to me:  http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#AssessmentDescriptorListType

**Comment by 4pins** [comment] 2022-08-31 21:41
Added to mapping (Assessments)!

**Closed as completed** 2023-08-11 19:17 UTC
Labels: ready, CEDS Gap, NADM 4.3
